---
- ansible.builtin.apt:
    update_cache: yes
    # upgrade: 'yes'

- ansible.builtin.apt:
    name:
      - certbot
      - curl
      - encfs
      - ffmpeg
      - imagemagick
      - jq
      - git
      - nginx
      - nmap
      - python3-certbot-nginx
      - screen
      - silversearcher-ag
      - tree
      - vim
      - zip
    state: present