#!/bin/bash

if [ $# == "0" ]; then
  echo ""
  echo "$0 <app name>"
  echo ""
  exit 2
fi

set -ex

name=$1
container_id=`docker ps | grep $name | cut -d' ' -f 1 | head -- -n 1`

docker logs --tail 50 --follow --timestamps $container_id

